import { CategoryConfig } from '@/types'

export const CATEGORIES: CategoryConfig[] = [
  {
    id: 'household',
    question: 'Who do you live with?',
    icon: '🏠',
    subtext: 'Start close to home. Think about everyone in your household over 18 — your partner, kids, roommates, parents, grandparents. You share an address, so you probably know their details.',
    examples: ['Your partner or spouse', 'Adult children at home', 'Roommates or housemates', 'A parent or grandparent who lives with you', 'An in-law in the house'],
    minSuggested: 5,
  },
  {
    id: 'close-family',
    question: 'Who are you closest to in your family?',
    icon: '❤️',
    subtext: 'Parents, siblings, adult kids who moved out, grandparents. Think of every family member you talk to at least monthly — you probably know where they live.',
    examples: ['Your mom or dad', 'Each brother or sister', 'Adult children in another city', 'A cousin who feels like a sibling', 'Grandparents'],
    minSuggested: 5,
  },
  {
    id: 'extended-family',
    question: 'What about the rest of your family in the state?',
    icon: '👪',
    subtext: 'Think about the holiday table. Aunts, uncles, cousins, in-laws, step-family — anyone in your state. List everyone you can think of.',
    examples: ['Aunts and uncles', 'Every cousin in the state', 'Your in-laws', 'Step-family members', 'Family friends who feel like family'],
    minSuggested: 5,
  },
  {
    id: 'best-friends',
    question: 'Who are your ride-or-die friends?',
    icon: '⭐',
    subtext: 'The people who would drop everything for you. The ones you text at 2am. You probably know their address and birthday. List every one of them.',
    examples: ['Your best friend since college', 'A childhood best friend', 'Someone you talk to every day', 'A former roommate you are still tight with'],
    minSuggested: 3,
  },
  {
    id: 'close-friends',
    question: 'Who else would you invite to your birthday dinner?',
    icon: '🎉',
    subtext: 'The next circle out — good friends you see regularly. Think through your group chats, your regular hangout crew, friends from different parts of your life.',
    examples: ['Friends from your neighborhood', 'A regular hangout crew', 'People from your group chat', 'Friends from college or high school', 'Couples you hang out with'],
    minSuggested: 8,
  },
  {
    id: 'neighbors',
    question: 'Who do you know on your street or in your building?',
    icon: '🏘️',
    subtext: 'Walk your block mentally. If you know their name, add them. You share a street — you might even know their address already.',
    examples: ['The neighbor you wave to', 'Someone you have borrowed something from', 'The person who watches your dog', 'The family across the street', 'The couple next door'],
    minSuggested: 4,
  },
  {
    id: 'coworkers',
    question: 'Who at work do you actually have a relationship with?',
    icon: '💼',
    subtext: 'The people you eat lunch with, grab coffee with, vent to. Current job and former colleagues you stay in touch with.',
    examples: ['A close colleague', 'Your work best friend', 'A manager or mentee you respect', 'Former coworkers you stay in touch with', 'Someone from a different department you click with'],
    minSuggested: 5,
  },
  {
    id: 'faith-community',
    question: 'Are you part of a faith community? Who do you know there?',
    icon: '⛪',
    subtext: 'Churches, mosques, synagogues, temples, spiritual groups — these are some of the deepest trust networks that exist. List everyone you know by name.',
    examples: ['Someone from your small group', 'A fellow member you see weekly', 'A pastor or leader you respect', 'A family from your congregation'],
    minSuggested: 4,
  },
  {
    id: 'school-pta',
    question: 'Who do you know through your kids\' school or education?',
    icon: '🏫',
    subtext: 'Fellow parents from the sideline, PTA members, teachers you know personally. School board races directly affect all of you.',
    examples: ['Parents from the soccer sideline', 'A PTA board member', 'A teacher you know outside school', 'The carpool crew', 'Another parent from birthday parties'],
    minSuggested: 4,
  },
  {
    id: 'sports-recreation',
    question: 'Do you play on any teams or do activities with people?',
    icon: '⚽',
    subtext: 'People you sweat with tend to trust each other. Think through every team, class, or regular activity.',
    examples: ['Your softball or basketball team', 'A hiking or running buddy', 'A yoga or gym regular', 'Golf or tennis partners', 'A climbing or cycling group'],
    minSuggested: 4,
  },
  {
    id: 'hobby-groups',
    question: 'What about book clubs, groups, or regular meetups?',
    icon: '📚',
    subtext: 'If you meet with people regularly around a shared interest, you have enough relationship for this conversation.',
    examples: ['Book club members', 'A crafting or knitting group', 'A gaming group', 'A volunteer org you are part of', 'A professional association'],
    minSuggested: 3,
  },
  {
    id: 'community-regulars',
    question: 'Who are the familiar faces in your daily life?',
    icon: '☕',
    subtext: 'The barista who knows your order. The person at the gym. The dog park regular. If you know their name, they are fair game.',
    examples: ['A coffee shop regular you chat with', 'Someone from the dog park', 'A neighbor from the farmers market', 'Your hairdresser or barber', 'A regular at your favorite bar'],
    minSuggested: 3,
  },
  {
    id: 'recent-meals',
    question: 'Who is the last person you had a meal with outside your home?',
    icon: '🍽️',
    subtext: 'Sharing a meal means trust. Think about your last few dinners out, lunches, brunches. Anyone we did not already cover?',
    examples: ['A lunch date from this week', 'Someone from a recent dinner out', 'A brunch crew member'],
    minSuggested: 2,
  },
  {
    id: 'who-did-we-miss',
    question: 'Who did we miss? Anyone else come to mind?',
    icon: '🤔',
    subtext: 'Scroll through your phone contacts and text messages right now. Is there anyone we did not ask about who you could have this conversation with?',
    examples: ['Someone from an old job', 'A friend of a friend you know well', 'Someone from an online community you know IRL', 'A former neighbor', 'Someone from a trip or event'],
    minSuggested: 3,
  },
]

export const TOTAL_STEPS = CATEGORIES.length
export const MINIMUM_PEOPLE_RECOMMENDED = 40
export const IDEAL_PEOPLE_COUNT = 50
